import { Command } from 'commander';
import Config from '../config.js';
import { Reporter } from '../reporters/index.js';
declare type Flags = {
    anyBranch: boolean;
    cleanup: boolean;
    yolo: boolean;
    publish: boolean;
    releaseDraft: boolean;
    tag: string;
    yarn: boolean;
    contents: string;
    otp?: string;
    out?: string;
    originalArgs: string[];
};
export declare function setFlags(commander: Command): void;
export declare function hasWrapper(): boolean;
export declare function run(config: Config, reporter: Reporter, flags: Flags, args: Array<string>): Promise<void>;
export {};
