declare function formatFunction(...strs: Array<string>): string;
export declare const defaultFormatter: {
    bold: typeof formatFunction;
    dim: typeof formatFunction;
    italic: typeof formatFunction;
    underline: typeof formatFunction;
    inverse: typeof formatFunction;
    strikethrough: typeof formatFunction;
    black: typeof formatFunction;
    red: typeof formatFunction;
    green: typeof formatFunction;
    yellow: typeof formatFunction;
    blue: typeof formatFunction;
    magenta: typeof formatFunction;
    cyan: typeof formatFunction;
    white: typeof formatFunction;
    gray: typeof formatFunction;
    grey: typeof formatFunction;
    stripColor: typeof formatFunction;
};
declare type FormatFunction = (...strs: Array<string>) => string;
export declare type FormatKeys = keyof typeof defaultFormatter;
export declare type Formatter = {
    bold: FormatFunction;
    dim: FormatFunction;
    italic: FormatFunction;
    underline: FormatFunction;
    inverse: FormatFunction;
    strikethrough: FormatFunction;
    black: FormatFunction;
    red: FormatFunction;
    green: FormatFunction;
    yellow: FormatFunction;
    blue: FormatFunction;
    magenta: FormatFunction;
    cyan: FormatFunction;
    white: FormatFunction;
    gray: FormatFunction;
    grey: FormatFunction;
    stripColor: FormatFunction;
};
export {};
